cicd: port 22 allow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,8 +21,7 @@ jobs:
       run: yarn install
 
     - name: Test SSH Connection
-      run: |
-        nc -zv ${{ secrets.HOST }} 22
+      run: nc -zv simplebank.my.id 22
 
     - name: Deploy to Server
       env:
@@ -36,11 +35,12 @@ jobs:
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
         ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER@$HOST" << 'EOF'
-          cd ~/FSW-Backend || exit 1
-          git pull origin development || exit 1
-          yarn install || exit 1
-          pm2 restart all || exit 1
-          sudo systemctl reload nginx || exit 1
+          echo "Connected to the server successfully."
+          cd ~/FSW-Backend || { echo "Failed to change directory"; exit 1; }
+          git pull origin development || { echo "Failed to pull from Git"; exit 1; }
+          yarn install || { echo "Failed to install dependencies"; exit 1; }
+          pm2 restart all || { echo "Failed to restart PM2"; exit 1; }
+          sudo systemctl reload nginx || { echo "Failed to reload Nginx"; exit 1; }
         EOF
 
     - name: Notify Success
